---
title: "p8105_hw2_yw3995"
author: "Yuxuan Wang"
date: "2023-10-04"
output: github_document
---

# Problem 0

```{r setup, include = FALSE}
library(tidyverse)
library(readxl)
```

# Problem 1

## Clean the data in pols-month.csv

```{r, message = FALSE}
pols_df = 
  read_csv(file = "./data/pols-month.csv") %>% 
  janitor::clean_names() %>% 
  separate(mon, into = c("year", "month", "day")) %>% 
  mutate(month = month.abb[as.numeric(month)]) %>% 
  mutate(president = ifelse(prez_dem == 0, "dem", "gop")) %>% 
  select(-prez_dem, -prez_gop, -day)

pols_df
```

## Clean the data in snp.csv

```{r, message = FALSE}
snp_df = 
  read_csv(file = "./data/snp.csv") %>% 
  janitor::clean_names() %>% 
  mutate(date = as.Date(date, format = "%m/%d/%y"),
         date = as.Date(ifelse(date > Sys.Date(),
                               format(date, "19%y-%m-%d"),
                               format(date)))) %>% 
  separate(date, into = c("year", "month", "day")) %>% 
  mutate(month = month.abb[as.numeric(month)]) %>% 
  select(-day) %>% 
  arrange(year, month) %>% 
  relocate(year, month)

snp_df
```

## Clean the data in unemployment.csv

```{r, message = FALSE}
unemployment_df = 
  read_csv(file = "./data/unemployment.csv") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "percentage") %>% 
  mutate(month = str_to_title(month))

unemployment_df$year = as.character(unemployment_df$year)

unemployment_df
```

## Merging

```{r, message = FALSE}
polssnp_df = 
  merge(pols_df, snp_df, by = c("year", "month")) %>% 
  arrange(year, month)
```

```{r, message = FALSE}
merge_df = 
  merge(polssnp_df, unemployment_df, by = c("year", "month")) %>% 
  arrange(year) %>% 
  relocate(year)
```